require("dotenv").config()
const express = require("express")
const app = express()
const sumbitRouter = require("./routes/sumbite_route")
const pageRouter = require("./routes/page_route")
const adminRouter = require("./routes/admin_route")
const nationalcodeRouter = require("./routes/nationalcodesumbite_route")
const teacherRouter = require("./routes/teacher_route")
const teachernationalcodeRouter = require("./routes/teachertnationalcodesumbite_route")
const teacheradminRouter = require("./routes/teacheradmin_route")
const chatbotRouter = require("./routes/chat_route")
app.use(express.json());
app.use(express.urlencoded({extended:true}))
app.use(express.static("public"))
app.use("/",sumbitRouter)
app.use("/api/dashboard",pageRouter)
app.use("/api/admin",adminRouter)
app.use("/api/nationalcode",nationalcodeRouter)
app.use("/teacher",teacherRouter)
app.use("/api/teachernationalcodeRouter",teachernationalcodeRouter)
app.use("/api/teacheradmin",teacheradminRouter)
app.use("/api/chat",chatbotRouter)
const PORT = process.env.APP_PORT || 3000
app.listen(PORT,()=>{
    console.log(`listen to ${PORT}`)
})